export const times = [
  {
    time: '14:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 15,
  },
  {
    time: '15:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 8,
  },
  {
    time: '16:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '17:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 3,
  },
  {
    time: '18:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '19:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 1,
  },
  {
    time: '20:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '21:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 3,
  },
  {
    time: '22:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '23:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 4,
  },
  {
    time: '00:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '01:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 7,
  },
  {
    time: '02:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 6,
  },
  {
    time: '03:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 5,
  },
  {
    time: '04:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '05:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 5,
  },
  {
    time: '06:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '07:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 7,
  },
  {
    time: '08:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 8,
  },
  {
    time: '09:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '10:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 9,
  },
  {
    time: '11:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
  {
    time: '12:00',
    iconName: 'cloud',
    iconNameSmall: 'umbrella',
    degree: 3,
  },
  {
    time: '13:00',
    iconName: 'umbrella',
    iconNameSmall: 'umbrella',
    degree: 2,
  },
];
