export default texts = {
    WEATHER_GUIDE: 'Weather Guide',
    GO_LOG: 'Go To Login Page',
    GO_REG: 'Go To Registration',
    GO_APP: 'Go To Appflow',
    SETTINGS: 'Settings',
    RETURN_REG: 'Return to HomeScreen',
    GEO: 'Geolocation',
    TEMP: 'Temperature',
    LOCK: 'Lock',
    NOTIFI: 'Notifications',
    BACKGROUND: 'Background',
    WEATHER_MAP: 'Weather-Map',
    WIDGETS: 'Widgets',
    TELL_US: 'Tell about problem',
    CONTACT: 'Contact us',
    LOG_OUT: 'Log Out',
    ADD_LOC: 'Press to add location',
    TEXT_IN1: 'Enter your email',
    TEXT_IN2: 'Enter your password',
    TEXT_IN3: 'Comfrim your password',
    WIND_VEL: 'Wind velocity',
    STATUS_PANEL: 'Status Panel',
    DONE: 'Done',
    Test_Title: 'What is Lorem Ipsum?',
    Test_Text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}