export default texts = {
    WEATHER_GUIDE: 'Weather Guide',
    GO_LOG: 'Go To Login Page',
    GO_REG: 'Go To Registration',
    GO_APP: 'Go To Appflow',
    SETTINGS: 'Settings',
    RETURN_REG: 'Return to HomeScreen',
    GEO: 'Geolocation',
    TEMP: 'Temperature',
    LOCK: 'Lock',
    NOTIFI: 'Notifications',
    BACKGROUND: 'Background',
    WEATHER_MAP: 'Weather-Map',
    WIDGETS: 'Widgets',
    TELL_US: 'Tell about problem',
    CONTACT: 'Contact us',
    LOG_OUT: 'Log Out',
    ADD_LOC: 'Press to add location',
    TEXT_IN1: 'Enter your email',
    TEXT_IN2: 'Enter your password',
    TEXT_IN3: 'Comfrim your password',
}